spring.application.name=api-gateway
server.port=8080

services.auth.url=${AUTH_SERVICE_URL}
services.account.url=${ACCOUNT_SERVICE_URL}
services.transaction.url=${TRANSACTION_SERVICE_URL}

cors.allowed-origin=${CORS_ALLOWED_ORIGINS}




#spring.cloud.gateway.mvc.routes[0].id=auth-service
#spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**
#
#spring.cloud.gateway.mvc.routes[1].id=customer-service
#spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/customers/**
#
#spring.cloud.gateway.mvc.routes[2].id=account-service
#spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082
#spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/accounts/**
#
#spring.cloud.gateway.mvc.routes[3].id=beneficiary-service
#spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8082
#spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/beneficiaries/**